<?php
namespace Sapphirecat\Signal;

use DomainException;

/** Signal handler registry. */
class Router
{
    /** Signal handler management.
     *
     * @var integer $seq Unique portion of the unique ID for signal handlers.
     * @var string $tag Fixed per-instance portion of the unique ID for signal
     * handlers.
     * @var array[callable] $stack Active signal handlers.
     */
    private $seq = 0;
    private $tag;
    private $stack = array();

    /** Constructor. */
    function __construct()
    {
        $this->tag = uniqid('.', true);
    }

    /** Add a signal handler to the active list.
     *
     * The newly-added signal handler will be first in line for receiving
     * signals.
     *
     * @param callable $handler Signal dispatching fuction to be invoked when a
     * signal is sent.
     * @return ScopeGuard Value that removes the signal handler when destroyed.
     */
    public function add(callable $handler, array $signals=null)
    {
        $id = ++$this->seq . $this->tag;
        $signalSet = isset($signals) ? array_flip($signals) : null;
        $this->stack[$id] = [$handler, $signalSet];
        return new CallScopeGuard([$this, 'remove'], [$id]);
    }

    /** Remove a signal handler from the active list.
     *
     * @param string $id ID generated by the add() function.
     * @return void
     * @throws DomainException if an invalid $id is given.
     */
    public function remove($id)
    {
        if (! isset($this->stack[$id])) {
            throw new DomainException("Unknown or previously unregistered handler: $id");
        }

        unset($this->stack[$id]);
    }

    /** Send a signal to the handlers.
     *
     * Returns if all handlers decline to handle the signal.
     *
     * @param string $signal Signal being sent.
     * @param array $args Arguments to pass to the signal handler.
     * @param Restarts $restarts Active restarts that may be invoked by a signal
     * handler.
     * @return void
     * @throws RestartInterface to transfer control when a restart is invoked by
     * a handler.  This exception SHOULD NOT be caught except by code that
     * defined the restart.
     */
    public function invoke($signal, array $args, Restarts $restarts)
    {
        foreach (array_reverse(array_values($this->stack)) as $handlerInfo) {
            list($handler, $signals) = $handlerInfo;
            if ($signals === null || isset($signals[$signal])) {
                call_user_func($handler, $restarts, $signal, $args);
            }
        }
    }
}
